# Generated by Django 2.1.7 on 2019-03-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('programming_language', models.CharField(max_length=30)),
                ('description', models.TextField(help_text="Enter a description of the book's topic", max_length=1024)),
                ('date_added', models.DateField()),
                ('book_author', models.ManyToManyField(help_text='Enter the author/s of the book.', to='core.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='books_authored',
            field=models.ManyToManyField(help_text='Names of all the books this author has contributed to', to='core.Book'),
        ),
    ]
