# Generated by Django 2.1.7 on 2019-03-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190311_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books_authored',
            field=models.ManyToManyField(blank=True, help_text='Names of all the books this author has contributed to', to='core.Book'),
        ),
    ]
