# Generated by Django 2.1.7 on 2019-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190311_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ManyToManyField(help_text='Enter the programming language this book covers', to='core.Book')),
            ],
        ),
    ]
