# Generated by Django 2.1.7 on 2019-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190313_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_slug',
            field=models.SlugField(default='a'),
        ),
    ]
